"""Catalogue claims stay qualified and all metadata remains inert."""

import contextlib
import copy
import io
import html
import json
import os
from pathlib import Path
import shutil
import tempfile
import unittest
from unittest.mock import patch

from scripts import generate_catalog as catalog

ROOT = Path(__file__).resolve().parents[1]


class CatalogTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name).resolve()
        for folder in ("experiments", "templates/experiment"):
            shutil.copytree(ROOT / folder, self.root / folder, ignore=shutil.ignore_patterns("__pycache__", "reports"))
        for name in ("catalog/evidence.json", "docs/evaluation.md"):
            path = self.root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / name, path)
        self.evidence_path = self.root / "catalog/evidence.json"
        self.evidence = json.loads(self.evidence_path.read_bytes())

    def build(self):
        with contextlib.redirect_stdout(io.StringIO()):
            return catalog.build_catalog(self.root)

    def write_evidence(self, value=None):
        self.evidence_path.write_text(json.dumps(self.evidence if value is None else value), encoding="utf-8")

    def manifest(self, name="market-brief", **changes):
        path = self.root / "experiments" / name / "experiment.json"
        value = json.loads(path.read_bytes())
        value.update(changes)
        path.write_text(json.dumps(value), encoding="utf-8")

    def test_deterministic_page_groups_all_seeds_and_qualifies_historical_evidence(self):
        text = self.build()
        self.assertEqual(text, self.build())
        for name, question in self.evidence["questions"].items():
            self.assertIn(question, html.unescape(text))
            self.assertIn(f"../experiments/{name}/README.md", text)
        self.assertEqual(text.count("| Maturity | Experimental |"), 3)
        self.assertEqual(text.count("| Native agent hosts | Unverified |"), 3)
        self.assertIn("2026-10-02", text)
        self.assertIn("dc530976b58fcc86db104ac7a173fca975c3718a", text)
        self.assertIn("0f82039759ef4db9d5b3dbd90f52863f8074f2a6", text)
        self.assertIn("12 fixed offline cases", text)
        self.assertIn("3.11.17", text)
        self.assertIn("author and AI review", text)
        self.assertIn("current-head verification", text)
        self.assertIn("human reproduction", text)
        self.assertIn("declared", text)
        self.assertNotIn(str(self.root), text)
        # Key and evidence ID ordering does not change the generated bytes.
        self.evidence["questions"] = dict(reversed(list(self.evidence["questions"].items())))
        self.evidence["offline_evaluation"]["experiments"].reverse()
        self.write_evidence()
        self.assertEqual(text, self.build())

    def test_unseen_experiment_is_listed_with_purpose_and_no_recorded_verification(self):
        target = self.root / "experiments/new-experiment"
        shutil.copytree(self.root / "templates/experiment", target)
        self.manifest("new-experiment", id="new-experiment", purpose="A new fictional experiment.")
        text = self.build()
        self.assertIn("## Other experiments", text)
        self.assertIn("../experiments/new-experiment/README.md", text)
        self.assertIn("A new fictional experiment&#46;", text)
        section = text.split("## Other experiments")[1]
        self.assertIn("Verification not recorded", section)
        self.assertIn("| Maturity | Experimental |", section)

    def test_every_promoted_or_archived_status_requires_a_future_reviewed_contract(self):
        for status in ("reproduced", "maintained", "graduated", "archived"):
            self.manifest(status=status)
            with self.assertRaisesRegex(catalog.CatalogError, "maturity"):
                self.build()

    def test_host_file_existence_never_becomes_supported(self):
        host = self.root / "experiments/market-brief/claimed-host.md"
        host.write_text("Fictional claim of a passed host; deliberately unreviewed.")
        self.manifest(tested_hosts=[{"name": "A host", "version": "1.2", "evidence": "claimed-host.md"}])
        text = self.build()
        self.assertIn("reported, unreviewed", text)
        self.assertIn("../experiments/market-brief/claimed-host.md", text)
        self.assertEqual(text.count("| Native agent hosts | Unverified |"), 3)
        self.assertNotIn("| Native agent hosts | Supported", text)
        host.unlink()
        with self.assertRaises(catalog.CatalogError):
            self.build()

    def test_markup_controls_and_links_are_inert_in_every_metadata_surface(self):
        hostile = "[Supported](https://evil.invalid) | <b>yes</b>\n## Maintained\t\u202e café"
        self.evidence["questions"]["market-brief"] = hostile
        self.write_evidence()
        host_file = "claim ) [link].md"
        (self.root / "experiments/market-brief" / host_file).write_text("Unreviewed synthetic claim.")
        self.manifest(purpose=hostile, access=hostile, cost=hostile,
                      tested_hosts=[{"name": hostile, "version": hostile, "evidence": host_file}],
                      command=["python3", "-c", "raise RuntimeError('must not execute')"])
        with patch("subprocess.Popen", side_effect=AssertionError("metadata executed")), \
             patch("socket.socket", side_effect=AssertionError("network attempted")):
            text = self.build()
        self.assertNotIn("[Supported](https://evil.invalid)", text)
        self.assertNotIn("\n## Maintained", text)
        self.assertNotIn("<b>", text)
        self.assertNotIn("\u202e", text)
        self.assertIn("&#92;u202E", text)
        self.assertIn("&#92;u000A", text)
        self.assertIn("&#92;u0009", text)
        self.assertIn("café", text)
        self.assertNotIn("must not execute", text)
        self.assertIn("../experiments/market-brief/claim%20%29%20%5Blink%5D.md", text)
        self.assertEqual(text.count("| Native agent hosts | Unverified |"), 3)

    def test_unknown_ids_and_invalid_evidence_are_actionable(self):
        original = copy.deepcopy(self.evidence)
        for modify in (lambda d: d["questions"].update(unknown="Unknown?"),
                       lambda d: d["offline_evaluation"]["experiments"].append("unknown"),
                       lambda d: d["offline_evaluation"]["experiments"].append("market-brief"),
                       lambda d: d["offline_evaluation"].update(date="2026-02-30"),
                       lambda d: d["offline_evaluation"].update(lab_revision="not-a-sha"),
                       lambda d: d["offline_evaluation"].update(passed_cases=True),
                       lambda d: d["offline_evaluation"].update(review_basis="human_reproduced"),
                       lambda d: d["offline_evaluation"].update(pull_request="javascript:alert(1)"),
                       lambda d: d.update(supported_hosts=["all"])):
            value = copy.deepcopy(original)
            modify(value)
            self.write_evidence(value)
            with self.assertRaises(catalog.CatalogError):
                self.build()

    def test_broken_local_references_and_escaping_or_symlink_paths_fail(self):
        for path in ("missing.md", "../outside.md", "/absolute.md", "docs/sub/C:file", "docs\\evaluation.md", "docs/./evaluation.md"):
            self.evidence["offline_evaluation"]["guide"] = path
            self.write_evidence()
            with self.assertRaises(catalog.CatalogError):
                self.build()
        self.evidence["offline_evaluation"]["guide"] = "docs/evaluation.md"
        self.write_evidence()
        guide = self.root / "docs/evaluation.md"
        guide.unlink()
        guide.symlink_to(ROOT / "docs/evaluation.md")
        with self.assertRaises(catalog.CatalogError):
            self.build()
        guide.unlink()
        guide.write_text("Synthetic guide.")
        (self.root / "experiments/market-brief/README.md").unlink()
        with self.assertRaises(catalog.CatalogError):
            self.build()

    def test_evidence_json_is_bounded_utf8_strict_and_never_reads_a_fifo(self):
        for raw in (b"{" + b" " * 65536, b"\xff", b'{"schema_version":1,"schema_version":1}', b'{"schema_version":NaN}'):
            self.evidence_path.write_bytes(raw)
            with self.assertRaises(catalog.CatalogError):
                self.build()
        if hasattr(os, "mkfifo"):
            self.evidence_path.unlink()
            os.mkfifo(self.evidence_path)
            with self.assertRaises(catalog.CatalogError):
                self.build()

    def test_write_check_and_validation_failure_preserve_existing_artifact(self):
        path = self.root / "catalog/README.md"
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(catalog.main(["--root", str(self.root)]), 0)
            good = path.read_bytes()
            self.assertEqual(catalog.main(["--root", str(self.root), "--check"]), 0)
            path.write_bytes(good + b"stale")
            self.assertEqual(catalog.main(["--root", str(self.root), "--check"]), 1)
            self.manifest(status="maintained")
            self.assertEqual(catalog.main(["--root", str(self.root)]), 1)
        self.assertEqual(path.read_bytes(), good + b"stale")

    def test_no_observation_and_removed_curated_questions_keep_every_experiment_visible(self):
        self.evidence.update(questions={}, offline_evaluation=None)
        self.write_evidence()
        text = self.build()
        self.assertEqual(text.count("Verification not recorded"), 3)
        self.assertEqual(text.count("| Maturity | Experimental |"), 3)
        self.assertIn("No offline evaluation observation is recorded", text)
        self.assertNotIn("fixed offline cases passed", text)

    def test_generated_output_symlink_is_refused_and_failed_replace_preserves_old_bytes(self):
        output = self.root / "catalog/README.md"
        untouched = self.root / "outside.md"
        untouched.write_bytes(b"preserve this synthetic file")
        output.symlink_to(untouched)
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(catalog.main(["--root", str(self.root)]), 1)
        self.assertEqual(untouched.read_bytes(), b"preserve this synthetic file")
        output.unlink()
        output.write_bytes(b"old catalogue")
        with patch.object(catalog.os, "replace", side_effect=OSError("synthetic failure")), \
             contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(catalog.main(["--root", str(self.root)]), 1)
        self.assertEqual(output.read_bytes(), b"old catalogue")
        self.assertEqual(list(output.parent.glob(".catalog-*")), [])

    def test_committed_generated_page_is_current(self):
        with contextlib.redirect_stdout(io.StringIO()):
            text = catalog.build_catalog(ROOT)
        self.assertEqual((ROOT / "catalog/README.md").read_bytes(), text.encode("utf-8"))


if __name__ == "__main__":
    unittest.main()
